### ISSUE TITLE
Реквест: возможность импорта меток.

### ISSUE THREAD

**Issue by JulyMorning** [troggy/anki-leo#11]
Было бы здорово и, я так полагаю, относительно несложно добавить эту фичу. В словарях некоторых из моих знакомых, в том числе и моем, есть обилие меток, присвоенных словам. Это делало обучение в лингволео поэтапным. В анки это тоже пришлось бы удобным -- учить те или иные слова по уже присвоенным меткам, например, по наборам из разговорников и всяком таком прочем.

К слову сказать, насколько реально осуществить некое подобие обратной синхронизации? Например, если карточка повторялась N количество раз и отложена на месяц вперед, то переводить это слово в разряд изученных на сервисе.

upd: а ещё было бы здорово, раз уж инвестированное время экспортировать, прихватить статус слова в тэге (новое, четверть, половина, почти, выученное).

**Comment by troggy** [comment]
а что за метки? Как их добавить? Не вижу такого в Лингуалео.

>  В анки это тоже пришлось бы удобным -- учить те или иные слова по уже присвоенным меткам, например, по наборам из разговорников и всяком таком прочем.

Это уже работает для наборов слов (раздел «Мои слова»), уже можно выгружать только неизученные слова, комбинировать эти фильтры (например, выгружать неизученные слова из такого-то набора). Попробуйте! :)

> К слову сказать, насколько реально осуществить некое подобие обратной синхронизации? Например, если карточка повторялась N количество раз и отложена на месяц вперед, то переводить это слово в разряд изученных на сервисе.

в текущей ситуации — нереально. Расширение просто выгружает слова в CSV и ничего не знает о их дальнейшей судьбе.

**Comment by JulyMorning** [comment]
Собственно, под метками я, пожалуй, и имел ввиду наборы слов. Назвать их на сервисе могут как угодно, но фактически [_это-таки они и есть_](https://dl.dropboxusercontent.com/u/7717507/leotag.PNG) :) 

> Это уже работает для наборов слов (раздел «Мои слова»), уже можно выгружать только неизученные слова, комбинировать эти фильтры (например, выгружать неизученные слова из такого-то набора). Попробуйте! :)

Однако же, хоть я этот момент еще не протестировал, предполагаю, речь идет о сугубо ручной выгрузке всех этих наборов по отдельности. Хотелось бы, чтобы вся эта инфорамация загружалась как бы по дефолту, независимо от того, что мы качаем: изученное, неизученное или что-то ещё, ведь это часть информации о слове. Так, уже в Anki, пользователь мог бы решать для себя, что именно сегодня изучать – всё подряд или же что-то конкретное, по тэгам.

> в текущей ситуации — нереально. Расширение просто выгружает слова в CSV и ничего не знает о их дальнейшей судьбе.

В смысле, написать что-то, что меняет статус слов на сервисе технически невозможно? В смысле, для этого требуется API, которого нет? Прост это был бы совершенно другой уровень качества изучения. Особенно, например, если бы мы могли присвоить в Anki тэги в духе «в кроссворд» или «в саванну», чтобы регулировать, куда именно что отправится. _upd: впрочем, я осознал, что то, о чем я говорю – это уже аддон в саму программу на пайтоне._

Так или иначе, благодарю за уже проделанный труд – захотелось хотя бы частично слезть с сервиса и унести всё нажитое непосильным трудом из-за их не самой здоровой организации обучения.

**Comment by JulyMorning** [comment]
К слову сказать, пытаюсь прикрутить скачанное к Anki в формате «cloze deletions» и постепенно прихожу к выводу, что если в самом файле вместо _some_word_ не будет прописано _{{c1::some_word}}_, сделать это не удастся. Я заблуждаюсь, и есть простое решение внутри программы, или же имеет смысл запилить фичу с импортом слов в этом формате? Был бы очень благодарен за решение этой заминки.

**Comment by troggy** [comment]
> Хотелось бы, чтобы вся эта инфорамация загружалась как бы по дефолту, независимо от того, что мы качаем: изученное, неизученное или что-то ещё, ведь это часть информации о слове.

Такую выгрузку сделать несложно. На праздниках постараюсь выделить время. Пока не знаю, как эту информацию импортировать в Анки, — поможете с этим?

> В смысле, написать что-то, что меняет статус слов на сервисе технически невозможно? В смысле, для этого требуется API, которого нет? 

Я полагаю, что менять статус слов на сервисе нет большой проблемы. Проблема только как расширение узнает, для какого слова какой статус проставлять — ведь расширение ничего не знает о жизни этих слов в Анки, изучены они или нет

> К слову сказать, пытаюсь прикрутить скачанное к Anki в формате «cloze deletions» и постепенно прихожу к выводу, что если в самом файле вместо some_word не будет прописано {{c1::some_word}}, сделать это не удастся. Я заблуждаюсь, и есть простое решение внутри программы, или же имеет смысл запилить фичу с импортом слов в этом формате? Был бы очень благодарен за решение этой заминки.

К своему стыду, даже не знал, что такой тип карточек существует. Выглядит полезно — надо сделать! Нужно `{{c1::some_word}}` использовать вместо слова в контексте? Давайте заведем отдельную задачу для этого.

**Comment by JulyMorning** [comment]
> Такую выгрузку сделать несложно. На праздниках постараюсь выделить время. Пока не знаю, как эту информацию импортировать в Анки, — поможете с этим?

На самом-то деле, вся задача только в выковыривании тегов с сервиса. Всё, что с ними нужно будет сделать в последствии – [_поместить в Anki при импорте как метки_](https://www.dropbox.com/s/eymnp7v7jrdokua/leotags.PNG?dl=0). Отдельное внимание уделить разве что возможности наличия нескольких тегов и разделить их запятыми. Да, не у всех такое есть, но у кого-то – бывает. Если дойдут руки, если будет не лень, то можно пойти еще дальше и импортировать сюда же в качестве меток [_другую информацию о слове_](https://github.com/troggy/anki-leo/issues/4). Так или иначе, не могу еще раз не поблагодарить за реализацию сего плагина. Жаль, что руководство сервиса не дает своим пользователям право распоряжаться своей информацией и выгружать словари нативными средствами, без бубнов.

> Проблема только как расширение узнает, для какого слова какой статус проставлять — ведь расширение ничего не знает о жизни этих слов в Анки, изучены они или нет

О том и речь, что для этого нужно уже плагин на Anki клепать. В целом, тоже не думаю, что с изменением статуса слова должны быть проблемы, но программа на пайтоне написана, а я его пока не настолько хорошо знаю, чтобы взяться. Внутри неё уже, вроде как, заложены какие-то правила, определяющие, что выучено, а что нет. Кажется, по умолчанию, это касается отложенных на 21+ день карточек.

> Нужно {{c1::some_word}} использовать вместо слова в контексте?

Тред создал, но этот момент там не прокомментировал. Если под словом в контексте имеется ввиду то самое, т.е. фактический контекст добавленного слова, то и такую строку, наверняка, кто-то мог бы использовать. Например, не в качестве более сложного «cloze deletion», а просто – в качестве «cloze», который, благо, выделяется всё тем же «cN». Например, можно было бы прописать к карточке hint, который по нажатию показывает предложение, но с отсутствующим словом, мол вспоминай по контексту, раз не помнишь. Смешно, но такого нет даже на самом сервисе. Пример:

```
Поле сортировки: Prejudice
Поле контекста: Prejudice is a disease.
Поле cN-контекста: {{c1::Prejudice}} is a disease.
```

И, да, сегодня еще вот такую штуковину нашел, она довольно досаждает: у слов и выражений без картинок в поле Image помещается «http:». Досада в том, что из-за этого поле и пустым не может считаться, но и функциональным тоже никак. В формате `<img scr="{{Image}}"</img>`, оно порождает кубики с вопросами. Сами теги при отсутствии картинки можно было бы исключить из карточки условным выражением `{{#Image}}<img scr="{{Image}}"</img>{{/Image}}`, но с наличием протокола в поле оно, разумеется, перестает работать.
Ещё раз благодарю. Надеюсь, мои репорты помогли.

**Comment by troggy** [comment]
спасибо! Ценные замечания.

Итого, что нужно сделать по этой задаче:

- [x] выгружать метки вместе со словами
- [x] обновить инструкцию информацией про метки

**Comment by JulyMorning** [comment]
*откладывает обучение в надежде на скорейшее появление новых фич*

:3

**Comment by troggy** [comment]
обновленная версия опубликована в стор. Спасибо за помощь!

@JulyMorning буду вам признателен за обновленный скриншот для инструкции по импорту. Старый: https://troggy.github.io/anki-leo/img/import.png. Новый скриншот должен отображать 7ое поле на Tags. 
У меня англоязычная версия Анки, поэтому пока я не найду как переключить язык (на удивление не нашёл сходу), скриншот не смогу обновить сам.

**Comment by JulyMorning** [comment]
К сожалению, на данный момент всё поломалось :) Сначала хотел спросить, но затем всё-таки открыл экспортированный файл для собственноручного анализа, узнать какие поля за что отвечают.

Как было:

`circumspect;осмотрительный;http://contentcdn.lingualeo.com/uploads/picture/3221157.png;ˈsɜrkəmˌspɛkt;;http://audiocdn.lingualeo.com/v2/3/8118-631152008.mp3`

Как стало:

`"circumspect";"осмотрительный";"http://contentcdn.lingualeo.com/uploads/picture/3221157.png";"ˈsɜrkəmˌspɛkt";;"http://audiocdn.lingualeo.com/v2/3/8118-631152008.mp3";"100_words_for_IELTS Из_Наборов"`

Во-первых, это кавычки, конечно. Второе – то, что, возможно, было и прежде, но заметилось только сейчас – в четвертое поле (транскрипция) вписывается `null`, если сама транскрипция отсутствует. В данном случае он тоже, кстати сказать, представляется в кавычках. Третье касается тегов: когда их несколько, они не выделяются между собой запятыми, а пробелы превращаются в нижнее подчеркивание, что не очень красиво. Пример такого случая выше: «Из Наборов» и «100 words for IELTS». Такой вот багрепорт :)

Как только заработает, конечно, не откажу и в изготовлении скриншотов. Язык Anki, вроде как, консольным параметром можно задать, только не припомню как именно. А ещё, если будут-таки готовы ещё и поля с нотациями пропусков, то метки логичнее в последнее поставить.

**Comment by troggy** [comment]
> К сожалению, на данный момент всё поломалось 

Что именно поломалось и как? Пока вижу только ошибку с транскрипцией

> Во-первых, это кавычки, конечно

чем именно мешают кавычки? Добавлены намерено

> в четвертое поле (транскрипция) вписывается null, если сама транскрипция отсутствует

это действительно непорядок. Исправлю

> Третье касается тегов: когда их несколько, они не выделяются между собой запятыми, а пробелы превращаются в нижнее подчеркивание, что не очень красиво.

Анки не понимает тэгов через запятую. Для Анки тэг — это одно слово. Тэги пишутся через пробел. Поэтому я специально меняю пробелы на подчеркивания. Если вы покажете, как в Анки можно ввести тэги с пробелами и через запятую — буду признателен.

**Comment by troggy** [comment]
~так, есть проблемы, если у слова нет транкрипции — вся строка ломается~

нет, всё же всё работает как надо. Выпускаю исправление для пустой транскрипии и жду подробностей от вас

**Comment by troggy** [comment]
если ломается импорт, то пришлите свой файл со словами

**Comment by JulyMorning** [comment]
Кавычки не нужны по ряду причин. Одна из них – чисто эстетическая, поскольку в самой Anki пользователю придется всюду их видеть без возможности выделить, например, ту же транскрипцию в квадратные скобки, получая ["ˈsɜrkəmˌspɛkt"] вместо [ˈsɜrkəmˌspɛkt]. То же самое и с остальными полями, скажем, ни к чему ведь видеть кавычки в английских словах и переводах, а без них импортировать не получится. Другая причина техническая, ведь для ссылок придется перепиливать карточки. Прежнее `<img src="{{Image}}">` можно заменить на `<img src={{Image}}>`, да, но есть ещё и `[sound:{{Sound}}]`, читающий ссылку без них. Вдобавок мы не сможем потом по-нормальному воспользоваться обработчиками/специализированными плагинами, которые делают всю медиатеку доступной локально.

Попробую что-нибудь пошаманить с тегами и новой версией – отпишусь. Если Anki на самом деле не воспринимает импорт нескольких меток через запятую, то это даже как-то странно. В конце концов, там написано «импорт меток», а не «импорт метки». Посмотрю.

**Comment by JulyMorning** [comment]
Попробовал на практике импорт файла с кавычками и осознал, что Anki считывает их адекватно и не заносит в поля – был неправ, что посчитал это недочетом. Насчет тегов: что ж, если у Anki именно такое понимание тегов, видимо, мы ничего с этим не сделаем, так что нижние подчеркивания – это вполне разумное решение в данном случае. Если версия 2.3.0 – это оно, то в транскрипциях, по-прежнему, null.

`"evening damp";"вечерняя сырость";;"null";;"http://audiocdn.lingualeo.com/v2/3/65816290-631170000.mp3";"Kindle"`

**Comment by troggy** [comment]
Версия 2.3.1 — уже доступна в маркете

**Comment by JulyMorning** [comment]
Всё работает прекрасно. Сегодня сделаю скриншоты, если всё ещё актуально.

**Comment by JulyMorning** [comment]
Посмотрел на [страницу](https://troggy.github.io/anki-leo/) и понял, что будет совсем некрасиво, если я сделаю скриншот с другой системы. В пару кликов наколдовал вот [это](https://www.dropbox.com/s/9fcke54ybj3jg70/ankiscreen.png?dl=0).

**Comment by troggy** [comment]
спасибо!
