### ISSUE TITLE
Реквест: считывание таблиц с сервиса duolingo.

### ISSUE THREAD

**Issue by JulyMorning** [troggy/anki-leo#12]
Да, я понимаю, это выходит за рамки anki-_leo_, но проекты очень похожи (примеры: [1](https://dl.dropboxusercontent.com/u/7717507/duo1.PNG), [2](https://dl.dropboxusercontent.com/u/7717507/duo2.PNG)). На гитхабе [есть](https://github.com/abesto/duolingo-to-anki/issues) нечто похожее, но оно не считывает аудио, не импортирует пол и, насколько я понял, не берет из сервиса имеющиеся примеры.

**Comment by troggy** [comment]
идея интересная, для другого проекта уже, конечно.

Вообще мне нравятся проекты, целью которых является «освобождение данных». Можно подумать о таком для «словарных» сервисов (duolingo, lingualeo, memrise и др.).

**Comment by troggy** [comment]
Можно реализовать в рамках проекта https://freeyourstuff.cc/
