### ISSUE TITLE
Экспорт словаря для тренировок «Cloze Deletion».

### ISSUE THREAD

**Issue by JulyMorning** [troggy/anki-leo#13]
Собственно, открываю отдельный тред по прежде упомянутому поводу – по поводу полезности запиливания специфического экспорта под тренировки в духе «конструктор слов», но в Anki. Вот [_здесь_](http://finpapa.ucoz.ru/ankitest-cloze.html) на русском языке можно подробнее узнать о том, как такие карточки оформляются. В общем и целом, нужно чтобы в настройке типа карточек были прописаны такие вещи как {{cloze::Word}} и {{type:cloze:Word}}. В результате можно получить на выходе нечто ([_превью_](https://www.dropbox.com/s/m38ibn8qse4h7dl/ankileo.PNG)), что заменит одну из наименее неоправданных – прошу простить за двойное отрицание – тренировок на веб-сервисе.

К сожалению, уровень моего знакомства с Anki позволяет предположить, что одних только настроек карточек типа «пропуски» не хватает, чтобы использовать в данном ключе уже загруженные слова. По крайней мере, мне удавалось решить вопрос только засчет ручной замены первого поля с `SomeWord` на `{{c1::SomeWord}}`, потому как именно тегом `{{сN::__}}` обозначается та часть карточки, которую нужно скрыть, иначе она не будет работать.

Саджест в следующем: насколько я понимаю, проблема должна катастрофически легко решаться засчет добавления нового поля в CSV, которое будет заключать в себя оригинальное слово, заключенное в фигурные скобки `c1`. Если кому-то это нужно, он просто использует это поле в этом контексте, а если нет – его можно игнорировать при импорте. Если вместо добавления нового поля сделать замену первого, то это породит массу дубликатов.

В том виде, в котором я себе это представляю, оно реализуется быстрее, чем написание этого репорта.

**Comment by troggy** [comment]
Добавим новое поле в CSV: 
- контекст с использованием cN нотации

Используя разные настройки импорта в Anki, из итогового файла можно будет создавать как и привычные колоды, так и cloze

**Comment by troggy** [comment]
Версия 2.4.0 улетела в маркет

**Comment by troggy** [comment]
Импорт: https://troggy.github.io/anki-leo/img/cloze.png

**Comment by JulyMorning** [comment]
Почему только «контекстная» версия пропусков, если не секрет? Пропуск одного слова тоже возможен – так Anki можно использовать как замену тренировке «конструктор слов». Опять-таки, если кому-то это не нужно, поле можно не импортировать.

Разумеется, и за уже проделанную работу – благодарю.

**Comment by JulyMorning** [comment]
Сразу захотелось проверить всё это на живых примерах, и вот что обнаружилось:

`"bedevil";"терзать";"http://contentcdn.lingualeo.com/uploads/picture/1627251.png";"bɪdˈevl";"It bedevils our decision-making in important ways";"http://audiocdn.lingualeo.com/v2/3/4734-631152008.mp3";"TED Слова_из_материалов";"It bedevils our decision-making in important ways"`

Те слова, чья форма в контексте была другой, не выделяются ни жирным, ни, соответственно, cloze-нотациями. Понимаю, что это довольно непростая проблема для решения, но, как вариант, такое cloze-поле можно просто ампутировать какой-нибудь проверкой на наличие слова из первого поля. Чуть более сложные варианты – проверки по наличию большей части последовательности символов и обрезание его по пробелам. Впрочем, это всего лишь то, что сходу пришло в голову.

**Comment by troggy** [comment]
> Чуть более сложные варианты – проверки по наличию большей части последовательности символов и обрезание его по пробелам. 

К сожалению, такое не будет работать для неправильных глаголов, например.

> Пропуск одного слова тоже возможен – так Anki можно использовать как замену тренировке «конструктор слов».

Как это будет работать? Можно пример?

**Comment by JulyMorning** [comment]
> Как это будет работать? Можно пример?

На первой стороне перевод и форма ввода. Оборотная сторона, соответственно, проверяет правописание.

> К сожалению, такое не будет работать для неправильных глаголов, например.

И то верно. Могу предположить, что их можно отсеять по списку, благо список не получится большим, хотя мне уже как-то не по себе что-то предлагать – и так было сделано достаточно много. В сущности, это вопрос перфекционизма. Такого рода контекстная проблема будет встречаться довольно часто, если люди активно используют «джунгли» или добавление слов из браузера. «Cloze» с одним словом этих сложностей не имеет, хоть и не так интересен.

**Comment by troggy** [comment]
> мне уже как-то не по себе что-то предлагать

Всё в порядке. Имеет смысл все предложения оформлять отдельными задачами. Не думаю, что я буду эту задачу делать сам, поскольку не пользуюсь клозе. Вся надежда на силу опенсорса — глядишь тот, кому нужно, пришлёт годный PR :)

**Comment by troggy** [comment]
> На первой стороне перевод и форма ввода. Оборотная сторона, соответственно, проверяет правописание.

Если я не ошибаюсь, то для этого можно использовать само слово, а {{cN:: подставить в шаблон карточки.

**Comment by JulyMorning** [comment]
> Если я не ошибаюсь, то для этого можно использовать само слово, а {{cN:: подставить в шаблон карточки.

Попробую, хотя в прошлый раз у меня, кажется, были какие-то проблемы с этим. Но пока что малину портит разве что весьма высокая вероятность встретить в новом поле контекстный пример без пропуска. Быть может, хотя бы простую проверку на дословное наличие слова из первого поля сделать? Уж лучше вообще не показывать такие карточки, чем показывать сразу ответы, ведь верно? Эх.

Однако же поддержка тегов категорически радует. Теперь можно пополнять словарный запас семантическими блоками, что логичнее.
