### ISSUE TITLE
Порядок полей -- "метки" удобнее сделать последними.

### ISSUE THREAD

**Issue by JulyMorning** [troggy/anki-leo#17]
Сейчас последними являются cloze-карточки, которые используются не всеми. Более того, Anki по умолчанию считает, что метки размещены именно в последнем поле, что может вызвать у кого-то замешательство, если он вручную не поменяет интерпретацию полей. Суммируя, сколько бы полей не было, теги -- в конце. Благодарю за нужное дело, юзаю во всю.

**Comment by troggy** [comment]
а это не нарушит ли обратную совместимость и в результате обратный эффект — у тех, кто импортировал метки из шестого поля, импорт сломается и нужно будет его перенастраивать?

**Comment by JulyMorning** [comment]
Не нарушит. Всё-таки при импорте потому программа и запрашивает, как интерпретировать поля, в каком столбце что находится.

**Comment by troggy** [comment]
проверил — текущим пользователям придётся менять настройки, т.е. нарушает обратную совместимость без веской причины. Добавляю новые поля в конец (например, «ассоциация»)
