### ISSUE TITLE
Новое поле -- cloze-карточки вариантов переводов.

### ISSUE THREAD

**Issue by JulyMorning** [troggy/anki-leo#18]
Было бы неплохо иметь такое поле, которое бы содержала в себе варианты переводов с cloze-нотациями. Зачем: допустим, у слова пять переводов. Это нормально при углубленном изучении обращать внимание на самые разнообразные значения слов. Особенно это может быть актуальным для фразовых глаголов, у которых этих значений масса. Что нужно: {{с1::перевод_первый}}, {{с2::перевод_второй}} и так далее. Что получится: если у слова пять переводов, Anki создаст пять разных карточек к такой записи. Таким образом, на каждой из карточек будут видны все варианты переводов кроме одного. Мне это видится чертовски удобным и, надо сказать, это ещё одна функция, которой нет в оригинальном сервисе.

И, да. Если перевод всего один, разумно было бы оставить поле пустым. Иначе это будет ещё один, правда, слегка отличающийся внешне вариант самой обычной карточки слово-перевод. Само собой, кому это не нужно, можно не импортировать. Если импортировать, но не создавать специальный тип карточки к колоде, то тоже мешать не будет.

**Comment by troggy** [comment]
не уверен, что я уловил идею

**Comment by JulyMorning** [comment]
Идея в том, чтобы учить не связку слово/все переводы, а слово/перевод_1, слово/перевод_2 – чтобы ни одно из значений не уходило из внимания. Пока один из вариантов перевода скрыт, остальные показаны.

**Comment by troggy** [comment]
закрываю. Не входит в задачи этого проекта («освободить данные из Lingualeo»)
