### ISSUE TITLE
Парсинг сторонних переводчиков на предмет переводов и контекста.

### ISSUE THREAD

**Issue by JulyMorning** [troggy/anki-leo#19]
Наверняка, это будет уже совсем другой уровень сложности и качества сего расширения, однако же просто поясню суть проблемы, которая, наверняка, есть не только у меня. Состоит из двух частей:

1. Многие из слов на сервисе переведены весьма однобоко и требуют ручных коррекций. Коррекции, в свою очередь, весьма рутинны. Зашел на сайт качественного переводчика, прочел, перенес руками.

2. Также есть масса слов, к которым по умолчанию не указан контекст. Опять-таки, для лучшего понимания употребления слова контекст желательно держать при себе. Снова заходим на сторонний сервис, переносим варианты употребления.

Всё это отнимает ну просто прорву времени. Было бы чертовски замечательно, если бы хотя бы частично это автоматизировалось. Если в списке переводов одно и то же слово значится несколько раз, то его можно делать жирным или подчеркивать -- так было бы наглядно и понятно, какое значение слова наиболее вероятно.

**Comment by troggy** [comment]
Слова в словарь lingualeo добавляются почти всегда из «живых» текстов в процессе чтения, а потом контекст всегда есть.

**Comment by JulyMorning** [comment]
Контекст, как правило, отражает только одно значение. У популярных слов их до двух десятков, у малоизвестных – два-три, с разными оттенками, но вместе с синонимами три-шесть. Чтобы понимать речь так, как мы понимаем родной язык, важно уловить не пару слово-перевод, а слово-образ. Образ возникает на основе ассоциативного ряда из всех значений и синонимов.
Впрочем, дело житейское, конечно.
