### ISSUE TITLE
Для удобства и читабельности: новый перевод с новой строки.

### ISSUE THREAD

**Issue by JulyMorning** [troggy/anki-leo#20]
Собственно, всё в заголовке. Когда несколько переводов следуют друг за другом водной строке, восприятие перестает быть последовательным, а запоминать всегда проще частями.

Для владельцев маленьких дисплеев, вероятно, потребовалась бы возможность выбора, т.е., опять же, флажок переключения.

**Comment by JulyMorning** [comment]
На самом деле, это можно объединить с соседним тредом:

— https://github.com/troggy/anki-leo/issues/23

Если у каждого перевода будет свой id, то, насколько я помню, можно будет реализовать перевод на новую строку уже через стили внутри анки.

**Comment by troggy** [comment]
https://github.com/troggy/anki-leo/issues/23#issuecomment-559533065
