### ISSUE TITLE
Cloze-контекстные карточки: известная беда.

### ISSUE THREAD

**Issue by JulyMorning** [troggy/anki-leo#21]
В общем, раз уж запостил целый ряд предложений, повешу и это. Как минимум, наличие проблемы таким образом не забудется.

В нынешнем варианте поле cloze/context содержит в себе {{c1::word}} только в том случае, если оно посимвольно повторяет первое поле с английским словом. В остальных случаях, если форма другая, поле заполняется контекстом без пропусков. Очень хочется использовать эту функцию ввиду её уникальности и отсутствия на львином сервисе, но пока проскальзывают карточки без пропусков, но будто бы сразу с ответами, это невозможно использовать для обучения. Если будет на это время, предлагаю решить это пусть даже самым простым и грубым образом -- проверять эти карточки на наличие слов из первого поля, и только потом обрабатывать их, добавляя {{c1::_}}. Таким образом, там где это условие не выполнено, эти поля просто не будут использоваться в карточках, не создавая тем самым конфузов. Более трудоемкий вариант, как я уже говорил, с чем-то вроде выявления нужного слова при достижении порога посимвольного совпадения с обрезкой по пробелам, но это и дольше, и, разумеется, не будет работать с неправильными глаголами (хотя, на мой взгляд, черт с ними).

**Comment by troggy** [comment]
Можно сделать хорошо используя что-то типа https://github.com/FinNLP/en-inflectors

**Comment by troggy** [comment]
закрываю. Не входит в задачи этого проекта («освободить данные из Lingualeo»)
