### ISSUE TITLE
Рандомайзер для озвучивания слов.

### ISSUE THREAD

**Issue by JulyMorning** [troggy/anki-leo#22]
Чтобы сделать изучение слов более разнообразным, можно прикрутить генератор случайной озвучки для женского и мужских вариантов британского и английского произношения. К частью, ссылки в грандиозных коррекциях нуждаться не будут. Все четыре варианта:

```
picturesque:

http://audiocdn.lingualeo.com/v2/**_0_**/30571-631152008.mp3
http://audiocdn.lingualeo.com/v2/**_1_**/30571-631152008.mp3
http://audiocdn.lingualeo.com/v2/**_2_**/30571-631152008.mp3
http://audiocdn.lingualeo.com/v2/**_3_**/30571-631152008.mp3
```

В сплывающем меню можно прикрутить галочки включения или отключения конкретных вариаций. Опять-таки, встроенной в сервис фичи такого образца, увы, нет. При запиливании всего упомянутого за последние пол часа, сей плагин, вероятно, будет достоин доната куда больше, чем текущий львиный функционал.

**Comment by troggy** [comment]
спорная фича. В любом случае она будет опциональной, а, значит, нужно добавлять окно настроек (или что-то подобное) в плагин — на мной вкус слишком много работы ради сомнительной пользы.

**Comment by JulyMorning** [comment]
Быть может, не меню, но хотя бы чекбокс? Не приоритетно, согласен, но всё-таки.

**Comment by troggy** [comment]
закрываю. Не входит в задачи этого проекта («освободить данные из Lingualeo»)
