### ISSUE TITLE
Уникальный стиль/класс/id для каждого перевода.

### ISSUE THREAD

**Issue by JulyMorning** [troggy/anki-leo#23]
Было бы славно, если бы при парсинге каждому из переводов присваивался уникальный стиль/класс/id, используя html-разметку. Так, это можно было бы использовать потом при должном форматировании карточек. Например, каждый из переводов выделить новым цветом, чтобы разграничть смыслы между собой или расположить их в удобной для отображения форме, используя CSS. Мелочь, но помогла бы радикально.

**Comment by troggy** [comment]
похоже, что ЛЛ больше не повзоляет добавлять несколько вариантов перевода. Мне не удалось это сделать — АПИ по-прежнему вовзращает только один перевод.
