### ISSUE TITLE
Плагин перестал работать. Похоже сайт Leo обновился.

### ISSUE THREAD

**Issue by testgit-1** [troggy/anki-leo#27]
Спасибо за ваше прекрасное расширение.

К сожалению сегодня плагин перестал работать. Перестала отображаться кнопка экспорта.
Скрин:
http://prntscr.com/ltlbhe

Похоже что проблема в том, что сайт обновился. 

Используется плагин 2.5.4
Chrome 70.0.3538.110 (Официальная сборка), (64 бит)

**Comment by troggy** [comment]
а если обновить сайт на странице словаря? Или напрямую по ссылке зайти https://lingualeo.com/ru/glossary/learn/dictionary ?

Если и в этом случае кнопка не появляется, сделайте, пожалуйста, скриншот окна браузера с открытой консолью разработчика. Как-то вот так:
1. На странице словаря лингулео нажмите Ctrl+Shift+J (Windows / Linux) или Cmd+Opt+J (Mac). Должна открыться консоль разработчика
2. Обновите страницу
3. Скриншот :)

**Comment by testgit-1** [comment]
Спасибо за оперативный ответ :)

Обновил хром до 71. Проблема решилась. Может дело было в этом.
http://prntscr.com/ltmp0m

**Comment by troggy** [comment]
Думаю, что хром ни при чём. Есть пара «секретных» ситуаций, при которых кнопка не появляется (например, если перейти со со страницы настроек на страницу словаря). Это моя недоработка :)
