### ISSUE TITLE
Неправильно стали выгружаться все слова.

### ISSUE THREAD

**Issue by alek-s-andr** [troggy/anki-leo#42]
На данный момент выгружается неправильно, сейчас выгрузил весь свой словарь, около 3000 слов, проверил csv файл, в нём каждое слово дублируется по 11 раз. Такое чувство что выгрузились 300 слов, каждое слово по 11 раз.
Попробовал выделить все слова (с помощью галочки выбрать все слова) и выгрузить выбранные, но выгрузились только те которые отображены на экране (28 слов), попробовал проскролить страницу вниз чтобы подгрузились и отобразились ещё слова на экране (около 100), нажал выгрузить выделенные (все слова в моём словаре), выгрузились только 100 отображенных на экране.

**Comment by troggy** [comment]
Спасибо за сообщение! Проблема известна как #39 и #40. Закрываю эту тема, как дубликат
