### ISSUE TITLE
Информации по дате последнего повторения слова

### ISSUE THREAD

**Issue by Gutalean** [troggy/anki-leo#5]
Здравствуйте, Константин!

Спасибо за расширение, оно очень полезное! Хотелось бы добавить возможность переноса слов вместе с информацией о дате их последнего повторения (хотя бы примерной), чтобы потом была возможность каким-то образом добавлять слова в Anki без необходимости разучивать их "с нуля".

**Comment by troggy** [comment]
@Gutalean сейчас есть возможность использовать фильтры ЛингуаЛео при экспорте. Например, скачать только неизученные слова. Возможно, это вам подойдёт.

**Comment by Gutalean** [comment]
Спасибо!
