### ISSUE TITLE
Протестировал версию 3.3.5

### ISSUE THREAD

**Issue by alek-s-andr** [troggy/anki-leo#50]
Попробовал выгрузить все слова (3291 в словаре), выгрузилось 2541, попробвал выбрать все и выгрузить выбранные, но тоже выгрузилось 2541 слово (и заметил, выбранные выгружаются помедленнее). Раньше при выгрузке процесс отображался как итерация по 300 слов, а сейчас проходит в данной последовательности: 295, 595, 895, 1195, 1495, 1795, 1808, 2108, 2408, 2541. В остальном вроде всё нормально.

**Comment by troggy** [comment]
Я пока не заметил пропавших слов в выгрузке, буду признателен, если кто-то изучит этот вопрос и укажет, что действительно каких-то слов не хватает.

 > выгружаются помедленнее

да, всё стало медленнее раза в два из-за дополнительных запросов к Лео для получения контекста слов.

**Comment by Racterrus** [comment]
Протестил тоже. В первую попытку зависло. Во вторую (скачивал "все" слова) у меня скачалось 8149 слов (строк в выгрузке) из 8037. При этом в выгрузке куча дублей... если почистить дубли через Excel, остается 422 строки.
Попробовал также выгрузить "выбранные" 100 штук, в этом случае все хорошо. Впрочем, это и в прошлой версии плагина работало нормально.

**Comment by Racterrus** [comment]
Перезагрузил бразузер, почистил кеш, в итоге загрузилось 7656 из 8037 при попытке выгрузить "все", зато почти без дублей (39 дублей нашел Excel).

**Comment by alek-s-andr** [comment]
При экспорте всех моих слов (3291 слово в словаре, на кнопке экспорта показывает что у меня 3296, скачивается только 2541) в консоли разработчика браузера выполняется 26 запросов к **api**, запросы из консоли сохранил к себе файлом локально в формате **har**, можно ли их сюда выложить чтобы вы посмотрели, или в них есть информация которая может быть использована для взлома (токены и т.п.)? Либо могу скинуть вам на электронную почту.

**Comment by Racterrus** [comment]
Возможно, меньшее число выгруженных слов - это баг ЛингваЛео. Я сосчитал вручную, в некоторых группах (например, "за прошлый месяц") фактически слов отображается меньше, чем показывает счетчик.
Отправил информацию о "пропадающих" словах в из словаря в техподдержку ЛингваЛео.

**Comment by troggy** [comment]
> Возможно, меньшее число выгруженных слов - это баг ЛингваЛео.

Да, я тоже склоняюсь к этой версии. У меня аналогичная ситуация https://github.com/troggy/anki-leo/issues/40#issuecomment-518014428

Больше всего меня беспокоят дубли. На моей выборке их нет, поэтому затрудняюсь найти ошибку пока. 

@Racterrus раз у тебя есть дубли, буду признателен за har-файл с запросами. На почту kosta@whoot.me. В файле токен авторизации, поэтому после выгрузки har перелогинься — токен должен смениться (если ребята из Лео не налажали).

Как сделать har файл: [видео](https://yadi.sk/i/dXtJvs8MUmprkg)

**Comment by alek-s-andr** [comment]
Сейчас попробовал сделать экспорт, выгрузились полное количество, 3305 из 3305 слов, но в файле одни дубли, 1 слово повторяется по 301 разу, по итогу без дублей только 305 слов.
Загрузка шла очень медленно, вначале первая порция примерно 300 сразу, а потом по 10 слов за запрос и так до самого конца экспорта, они видимо опять поменяли **API** или что.

**Comment by troggy** [comment]
@itfork можешь прислать har-файл с запросами (см. коммент выше) ?

**Comment by alek-s-andr** [comment]
Сделал экспорт, получилось 2572 слова из 3327 в словаре, отправил вам на почту har файл с запросами и результат выгрузки csv (на всякий случай).

**Comment by troggy** [comment]
@itfork есть понимание, что выгрузились не все слова? Т.е. ты видишь слова, которые есть на Лингуалео, но нет в выгрузке?

**Comment by alek-s-andr** [comment]
@troggy проверил сейчас словарь на сайте, показывает что у меня 3417 слов, я попробовал посчитать вручную (через консоль браузера с помощью js), получилось что по факту, когда все слова прогрузились на странице 2596 слов, при экспорте слов вышло 2662 слова без дублей (получается экспорт работает нормально, даже больше выгрузилось на 66 слов чем прогруажется на странице словаря).
Проверил все наборы слов на сайте (по датам), везде сходятся с общей цифрой по дате, кроме одного набора слов, где указано "1 year ago: 2268", проверил в этом наборе вручную, по факту 1447 слов, почему так не знаю, написал в техподдержку lingualeo, буду ждать что ответят.

**Comment by alek-s-andr** [comment]
Техподдержка написала что отправили данную проблему разработчикам (26 сентября). Сегодня проверил экспорт, работает правильно, все слова выгрузились. Когда именно они исправили я не знаю, так как больше мне не писали а проверил я только сегодня.

**Comment by troggy** [comment]
Я думаю, что Лингуалео не исправили ничего, потому что на сайте все
по-прежнему плохо, если не хуже.

Расширение теперь использует старую версию АПИ Лингуалео, которая работает
лучше чем новая. Лингуалео использует новую.
