### ISSUE TITLE
Support Turkish

### ISSUE THREAD

**Issue by troggy** [troggy/anki-leo#55]
- [x] add locale
- [x] Create web store assets
- [x] Create web store description
- [x] Create Anki import instruction

**Comment by bariskisir** [comment]
#56 locale added

**Comment by troggy** [comment]
@bariskisir Thanks! 🙏

I would appreciate your translation for project description for Chrome webstore: https://github.com/troggy/anki-leo/blob/master/resources/webstore/description.tr.txt

**Comment by bariskisir** [comment]
#60 here it is

**Comment by troggy** [comment]
@bariskisir Hey 👋

by any chance if are have time and desire to translate these pages into Turkish?
https://github.com/troggy/anki-leo/blob/gh-pages/tr/index.md
https://github.com/troggy/anki-leo/blob/gh-pages/tr/card-template.md

Plus few strings here:
https://github.com/troggy/anki-leo/blob/gh-pages/_layouts/basic_tr.html#L5
https://github.com/troggy/anki-leo/blob/gh-pages/_layouts/basic_tr.html#L15

**Comment by bariskisir** [comment]
#84 here it is

**Comment by troggy** [comment]
Merged with a [tiny addition](https://github.com/troggy/anki-leo/commit/c32ef59b70fb32ef332024677a81978704767f2c). @bariskisir you are awesome 🚀
