### ISSUE TITLE
Support Spanish

### ISSUE THREAD

**Issue by troggy** [troggy/anki-leo#58]
- [x] add locale
- [x] Create web store assets
- [x] Create web store description. Translate [this file](https://github.com/troggy/anki-leo/blob/master/resources/webstore/description.es.txt) to Spanish
- [x] Create Anki import instruction

**Comment by daviddetorres** [comment]
I can help with the translation of the file for the web store description to Spanish. I'll send PR.

**Comment by troggy** [comment]
@daviddetorres that's amazing! Gracias!

I have an instruction on how to import the words from CSV to Anki. So far it is only in Russian, but I plan to translate it into English. Would you be interested to translate this one as well, once it is in English?

**Comment by daviddetorres** [comment]
Sure! Just ping me and I'll PR the translation ;)

**Comment by troggy** [comment]
@daviddetorres 👋

If you are still up to translate, here are the files to translate:
https://github.com/troggy/anki-leo/blob/gh-pages/es/index.md
https://github.com/troggy/anki-leo/blob/gh-pages/es/card-template.md

Thanks :)

**Comment by daviddetorres** [comment]
Sure! Count with it 👍🏼 
I will book some time this week to do it and I'll send the PR 😸
