### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by alex-lokk** [troggy/anki-leo#75]
I'm totally happy with the plugin!

Learned more than 1000 English words so far...
![image](https://user-images.githubusercontent.com/429169/84380576-3b15b300-abf0-11ea-957f-b554de6a5a99.png)

The only issue I've found is that "donation" button allows only 100 RUB, I had to change the code from browser to send more :) :)
![image](https://user-images.githubusercontent.com/429169/84380482-10c3f580-abf0-11ea-8051-cd01639c4a94.png)

**Comment by troggy** [comment]
wow, thank you :) Gonna change donation form 😅

**Comment by troggy** [comment]
using form now 5525cb25a702b7cc76ca16231f371c95ffffc2ae
