### ISSUE TITLE
GetWords response has changed

### ISSUE THREAD

**Issue by dreambit** [troggy/anki-leo#78]
GetWords api has changed, now it returns words grouped by name.

Please update your code.

**Comment by dreambit** [comment]
Context is also stopped working, is empty in csv

**Comment by troggy** [comment]
спасибо за репорт!

**Comment by troggy** [comment]
I was deliberately using older version of their API, because the newer version was broken back then (see https://github.com/troggy/anki-leo/pull/52). Maybe this time something has changed

**Comment by troggy** [comment]
PR work in progress: https://github.com/troggy/anki-leo/pull/79

Works for me already, I will make some refactorings and extra tests before publishing
